/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 005e229466fa91524063c692d96ca2b8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "InterviewDbDO";
	}
	interface Env {
		ASSETS: Fetcher;
		AI_PROVIDER: string;
		OPENAI_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		OPENROUTER_API_KEY: string;
		OPENAI_MODEL: string;
		ANTHROPIC_MODEL: string;
		OPENROUTER_MODEL: string;
		INTERVIEW_DB: DurableObjectNamespace<import("./src/worker").InterviewDbDO>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_PROVIDER" | "OPENAI_API_KEY" | "ANTHROPIC_API_KEY" | "OPENROUTER_API_KEY" | "OPENAI_MODEL" | "ANTHROPIC_MODEL" | "OPENROUTER_MODEL">> {}
}
