/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 10286db9bbf3418dc7f3258355a109f8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "InterviewDbDO";
	}
	interface Env {
		ASSETS: Fetcher;
		INTERVIEW_DB: DurableObjectNamespace<import("./src/worker").InterviewDbDO>;
	}
}
interface Env extends Cloudflare.Env {}
